# Regular expressions match against the values of the enumeration org.bukkit.Material
# see Material enum here: http://jd.bukkit.org/doxygen/d7/dd9/namespaceorg_1_1bukkit.html

enable_switching_regex_doc: |
    Enable block click switching when the held item matches the following pattern (use AIR to specify an empty hand)
enable_switching_regex: .*_AXE|.*_PICKAXE|.*_SPADE|AIR
